### ISSUE TITLE
 NativeInterface.GetDiscoveredServices does not return the expected services on Windows Standalone, but it does on android

### ISSUE THREAD

**Issue by mark-kray** [GameWithPixels/PixelsUnityPlugin#1]
On Windows standalone: after connecting to a peripheral with `NativeInterface.ConnectPeripheral(handle, null, true, ConnectionRequestSent);`
`NativeInterface.GetDiscoveredServices(handle); ` returns a single `00000000-0000-1000-8000-00805F9B34FB` guid. (Internally, `WinRTNativeInterfaceImpl sgBleGetDiscoveredServices()` returns an empty string).

The same code deployed on android returns all the expected services.

However, if NativeInterface.ConnectPeriphera is called with a list that contains one of the service GUID's, `NativeInterface.GetDiscoveredServices(handle); ` returns all the expected services.

Can this issue be fixed?

**Comment by obasille** [comment]
Fixed with #2
